nix: Update nix-darwin stateVersion
To avoid:

    error: Build user group has mismatching GID, aborting activation
    The default Nix build user group ID was changed from 30000 to 350.
    You are currently managing Nix build users with nix-darwin, but your
    nixbld group has GID 3000, whereas we expected 30000.

    Possible causes include setting up a new Nix installation with an
    existing nix-darwin configuration, setting up a new nix-darwin
    installation with an existing Nix installation, or manually increasing
    your `system.stateVersion` setting.

    You can set the configured group ID to match the actual value:

        ids.gids.nixbld = 3000;

    We do not recommend trying to change the group ID with macOS user
    management tools without a complete uninstallation and reinstallation
    of Nix.

`mbp16` needed fixing with:

    sudo dscl . -create /Groups/nixbld PrimaryGroupID 350
    for i in {1..32}; do sudo dscl . -create /Users/_nixbld$i PrimaryGroupID 350; done
    sudo chown -R :350 /nix